### ISSUE TITLE
acc为0

### ISSUE THREAD

**Issue by dwangxxx** [heshuting555/NAIC_Person_ReID_DMT#6]
你好，我想请问一下，我训练自己的数据，训练了两个epoch之后，虽然loss一直在慢慢降低，但是acc还是一直为0，这是为什么啊

**Comment by heshuting555** [comment]
因为fc参数要重新训练，所以acc前面接近0，后面acc会上升的呢～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WangDeng <notifications@github.com&gt;
发送时间: 2020年9月27日 11:19
收件人: heshuting555/NAIC_Person_ReID_DMT <NAIC_Person_ReID_DMT@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[heshuting555/NAIC_Person_ReID_DMT] acc为0 (#6)





 
你好，我想请问一下，我训练自己的数据，训练了两个epoch之后，虽然loss一直在慢慢降低，但是acc还是一直为0，这是为什么啊

**Comment by dwangxxx** [comment]
> 因为fc参数要重新训练，所以acc前面接近0，后面acc会上升的呢～ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: WangDeng <notifications@github.com&gt; 发送时间: 2020年9月27日 11:19 收件人: heshuting555/NAIC_Person_ReID_DMT <NAIC_Person_ReID_DMT@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[heshuting555/NAIC_Person_ReID_DMT] acc为0 (#6) 你好，我想请问一下，我训练自己的数据，训练了两个epoch之后，虽然loss一直在慢慢降低，但是acc还是一直为0，这是为什么啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

非常感谢！

**Comment by heshuting555** [comment]
不客气呢～^_^





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WangDeng <notifications@github.com&gt;
发送时间: 2020年9月27日 21:03
收件人: heshuting555/NAIC_Person_ReID_DMT <NAIC_Person_ReID_DMT@noreply.github.com&gt;
抄送: heshuting555 <1173718914@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[heshuting555/NAIC_Person_ReID_DMT] acc为0 (#6)





  
因为fc参数要重新训练，所以acc前面接近0，后面acc会上升的呢～ 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: WangDeng <notifications@github.com&gt; 发送时间: 2020年9月27日 11:19 收件人: heshuting555/NAIC_Person_ReID_DMT <NAIC_Person_ReID_DMT@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[heshuting555/NAIC_Person_ReID_DMT] acc为0 (#6) 你好，我想请问一下，我训练自己的数据，训练了两个epoch之后，虽然loss一直在慢慢降低，但是acc还是一直为0，这是为什么啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
非常感谢！

**Comment by 4524353245** [comment]
您好，我也有这个问题，在训练了10个epoch以后acc 仍然为零，而且loss值降的很快，最初的大小只有5.4,一个iteration就会降0.1左右，请问这是什么情况呢？试了一些办法，没有解决

**Comment by heshuting555** [comment]
是用的Ranger优化器嘛？可能是Ranger优化器使得收敛趋势有点不稳定呢？
